{"name": "Login valid user", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: one of ('E', 'r', 'r', 'o', 'r', ' ', 'P', 'a', 'g', 'e')\n     but: was 'Welcome Page'\n\n", "trace": "  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\login.py\", line 22, in step_impl\n    assert_that (\"Welcome Page\", is_in(context.browser.title) )\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\hamcrest\\core\\assert_that.py\", line 43, in assert_that\n    _assert_match(actual=arg1, matcher=arg2, reason=arg3)\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\hamcrest\\core\\assert_that.py\", line 57, in _assert_match\n    raise AssertionError(description)\n"}, "steps": [{"name": "Given I navigate to login page", "status": "passed", "start": 1594110610136, "stop": 1594110610643}, {"name": "Then I login with \"abc\" and \"abcabc\"", "status": "passed", "start": 1594110610644, "stop": 1594110612822}, {"name": "Then I login Successfully", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: one of ('E', 'r', 'r', 'o', 'r', ' ', 'P', 'a', 'g', 'e')\n     but: was 'Welcome Page'\n\n", "trace": "  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\login.py\", line 22, in step_impl\n    assert_that (\"Welcome Page\", is_in(context.browser.title) )\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\hamcrest\\core\\assert_that.py\", line 43, in assert_that\n    _assert_match(actual=arg1, matcher=arg2, reason=arg3)\n  File \"c:\\users\\johnson_zhong\\pycharmprojects\\behavedemo\\venv\\lib\\site-packages\\hamcrest\\core\\assert_that.py\", line 57, in _assert_match\n    raise AssertionError(description)\n"}, "attachments": [{"name": "screenshot", "source": "ba5e6408-b7fa-41ec-abc4-48abdda87bfd-attachment.png", "type": "image/png"}], "start": 1594110612825, "stop": 1594110613413}], "start": 1594110605145, "stop": 1594110616461, "uuid": "1a018686-f466-4d94-958a-f270de1b2927", "historyId": "828847bd755f080eb1fdaf1ea16e8c0d", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "login_fail"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login & Logout"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}